export const PRODUCTS = {
  favoritesItems: [
    {
      id: 0,
      img: './img/pages/favorites/Rectangle 62.png',
      title: 'Velvet Covvered',
      colors: ['#9E6344', '#8F8E73'],
      price: 30,
    },
    {
      id: 1,
      img: './img/pages/favorites/Rectangle 47.png',
      title: 'CANDLE IN GLASS HOLDER',
      colors: ['#9F9189'],
      price: 30,
    },
    {
      id: 2,
      img: './img/pages/favorites/Rectangle 48.png',
      title: 'METAL PHOTO FRAME',
      colors: ['#F2C94C', '#828282'],
      price: 30,
    },
    {
      id: 3,
      img: './img/pages/favorites/Rectangle 65.png',
      title: 'Round flo or mat',
      colors: ['#ACAD92 ', '#D4CEBF'],
      price: 30,
    },
    {
      id: 4,
      img: './img/pages/favorites/Rectangle 66.png',
      title: 'Class light holder',
      colors: ['#A04F48', '#7B3D39'],
      price: 30,
    },
    {
      id: 5,
      img: './img/pages/favorites/Rectangle 67.png',
      title: 'Flannel Duvet Cover Set',
      colors: ['#9B9A98', '#A2A285 '],
      price: 30,
    },
    {
      id: 6,
      img: './img/pages/favorites/Rectangle 62.png',
      title: 'Fitted Cotton Sheet',
      colors: ['#DDEDD6', '#F3DDD8', '#C4BDB6'],
      price: 30,
    },
    {
      id: 7,
      img: './img/pages/favorites/Rectangle 67.png',
      title: 'Small Candle in a Small Jar',
      colors: ['#633733', '#BBBAC0', '#D8B4A2'],
      price: 30,
    },
    {
      id: 8,
      img: './img/pages/favorites/Rectangle 72.png',
      title: 'Checked Duvet Cover Set',
      colors: ['#81352D', '#A7A689 '],
      price: 30,
    },
    {
      id: 9,
      img: './img/pages/favorites/Rectangle 47.png',
      title: 'Washed Linen Pillowcase',
      colors: ['#888687', '#B6A899', '#A6A68B '],
      price: 30,
    },
    {
      id: 10,
      img: './img/pages/favorites/Rectangle 65.png',
      title: 'Ribbed Wool-blend Throw',
      colors: ['#D1C3B1', '#DDC1B2 '],
      price: 30,
    },
    {
      id: 11,
      img: './img/pages/favorites/Rectangle 77.png',
      title: 'Mini Porcelain Dish',
      colors: ['#DDEDD6', '#F3DDD8', '#C4BDB6'],
      price: 30,
    },
  ],

  galleryItems: [
    {
      id: 0,
      title: 'toimisto',
      img: './img/pages/gallery/toimisto.jpeg',
    },
    // {
    //   id: 1,
    //   title: 'äänistudio',
    //   img: './img/pages/gallery/äänistudio.jpeg',
    // },
    {
      id: 2,
      title: 'lääkärin',
      img: './img/pages/gallery/laakarin.jpg',
    },
    {
      id: 3,
      title: 'ravintola',
      img: './img/pages/gallery/ravintola.jpeg',
    },
    // {
    //   id: 4,
    //   title: 'äänistudio',
    //   img: './img/pages/gallery/äänistudio.jpeg',
    // },
    {
      id: 5,
      title: 'käytävä',
      img: './img/pages/gallery/kaytava.jpeg',
    },
    {
      id: 6,
      title: 'olohuone',
      img: './img/pages/gallery/olohuone.jpeg',
    },
    {
      id: 7,
      title: 'makuuhuone',
      img: './img/pages/gallery/makuuhuone.jpeg',
    },
    {
      id: 8,
      title: 'lastenhuone',
      img: './img/pages/gallery/lastenhuone.jpeg',
    },
    {
      id: 9,
      title: 'kylpyhuone',
      img: './img/pages/gallery/kylpyhuone.jpeg',
    },
    {
      id: 10,
      title: 'Parturikampaamo',
      img: './img/pages/gallery/parturikampaamo.jpeg',
    },
    {
      id: 11,
      title: 'hotelli',
      img: './img/pages/gallery/hoteli.jpeg',
    },
    {
      id: 11,
      title: '3d-konsepti olohuoneeseen',
      img: './img/pages/gallery/3d-konspecti.jpeg',
    },
  ],

  moduleoPage: [
    {
      id: 0,
      img: './img/pages/favorites/Rectangle 62.png',
      title: 'Velvet Covvered',
      colors: ['#9E6344', '#8F8E73'],
      price: 30,
    },
    {
      id: 1,
      img: './img/pages/favorites/Rectangle 47.png',
      title: 'CANDLE IN GLASS HOLDER',
      colors: ['#9F9189'],
      price: 30,
    },
    {
      id: 2,
      img: './img/pages/favorites/Rectangle 48.png',
      title: 'METAL PHOTO FRAME',
      colors: ['#F2C94C', '#828282'],
      price: 30,
    },
    {
      id: 3,
      img: './img/pages/favorites/Rectangle 65.png',
      title: 'Round flo or mat',
      colors: ['#ACAD92 ', '#D4CEBF'],
      price: 30,
    },
    {
      id: 4,
      img: './img/pages/favorites/Rectangle 66.png',
      title: 'Class light holder',
      colors: ['#A04F48', '#7B3D39'],
      price: 30,
    },
    {
      id: 5,
      img: './img/pages/favorites/Rectangle 67.png',
      title: 'Flannel Duvet Cover Set',
      colors: ['#9B9A98', '#A2A285 '],
      price: 30,
    },
    {
      id: 6,
      img: './img/pages/favorites/Rectangle 62.png',
      title: 'Fitted Cotton Sheet',
      colors: ['#DDEDD6', '#F3DDD8', '#C4BDB6'],
      price: 30,
    },
    {
      id: 7,
      img: './img/pages/favorites/Rectangle 67.png',
      title: 'Small Candle in a Small Jar',
      colors: ['#633733', '#BBBAC0', '#D8B4A2'],
      price: 30,
    },
    {
      id: 8,
      img: './img/pages/favorites/Rectangle 72.png',
      title: 'Checked Duvet Cover Set',
      colors: ['#81352D', '#A7A689 '],
      price: 30,
    },
    {
      id: 9,
      img: './img/pages/favorites/Rectangle 47.png',
      title: 'Washed Linen Pillowcase',
      colors: ['#888687', '#B6A899', '#A6A68B '],
      price: 30,
    },
    {
      id: 10,
      img: './img/pages/favorites/Rectangle 65.png',
      title: 'Ribbed Wool-blend Throw',
      colors: ['#D1C3B1', '#DDC1B2 '],
      price: 30,
    },
    {
      id: 11,
      img: './img/pages/favorites/Rectangle 77.png',
      title: 'Mini Porcelain Dish',
      colors: ['#DDEDD6', '#F3DDD8', '#C4BDB6'],
      price: 30,
    },
  ],
};
