import { Inter } from 'next/font/google';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import { BasketContextProvider } from '@/context/BasketContext';
import '../styles/globals.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Kraab Systems',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="fi">
      <head>
        <link rel="icon" type="image/svg+xml" href="/favicon.png" />
      </head>
      <body className={inter.className}>
        <BasketContextProvider>
          <Header />
          <main className="wrapper main">{children}</main>
          <Footer />
        </BasketContextProvider>
      </body>
    </html>
  );
}
